using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace V3SaveManager
{
	public partial class Savefile
	{
		public void WriteSave(string newfile)
		{

			if (File.Exists(newfile))
			{
				File.Delete(newfile);
			}

			using (FileStream fs = new FileStream(newfile, FileMode.CreateNew))
			{
				using (BinaryWriter bw = new BinaryWriter(fs, Encoding.Unicode))
				{
					bw.Write(this.GameName);
					bw.Write(this.ChapterName);
					bw.Write(this.SaveDetails);
					bw.Write(this.NewSaveData);
					bw.Write(this.Unk1);
					bw.Write(this.Unk2);
					bw.Write(this.Unk3);
					bw.Write(this.Unk4);
					bw.Write(this.Monocoins);
					bw.Write(this.Unk5);
					bw.Write(this.Unk6);
					bw.Write(this.Unk7);
					bw.Write(this.Unk8);
					bw.Write(this.PlayTime);
					bw.Write(this.Unk9);
					bw.Write(this.ToDo1);
					bw.Write(this.BGMVolume);
					bw.Write(this.SFXVolume);
					bw.Write(this.VoicesVolume);
					bw.Write(this.ReticleSpeed);
					bw.Write(this.MovementBob);
					bw.Write(this.Controls);
					bw.Write(this.LookInvert);
					bw.Write(this.TextSpeed);
					bw.Write(this.MapDisplay);
					bw.Write(this.Setting1);
					bw.Write(this.LogicDifficulty);
					bw.Write(this.ActionDifficulty);
					bw.Write(this.IsContinueEnabled);
					bw.Write(this.GameClearFlg);
					bw.Write(this.ToDo2);
					bw.Write(this.Unk10);
					bw.Write(this.CurrentLevel);
					bw.Write(this.TotalEXP);
					bw.Write(this.Unk11);
					bw.Write(this.Unk12);
					bw.Write(this.CurrentLevelShort);
					bw.Write(this.Unk13);
					bw.Write(this.Unk14);
					bw.Write(this.MapPositionX);
					bw.Write(this.MapPositionY);
					bw.Write(this.Unk15);
					bw.Write(this.ToDo3);
					bw.Write(this.IsStatusAlive);
					bw.Write(this.IsStatusUnknown);
					bw.Write(this.ToDo4);
					bw.Write(this.MonopadTheme);
					bw.Write(this.BeforeText);
					bw.Write(this.BacklogText);
					bw.Write(this.ToDo5);
					bw.Write(this.CasinoCoins);
					bw.Write(this.Unk16);
					bw.Write(this.GDeathCardMachine);
					bw.Write(this.Unk17);
					bw.Write(this.Unk18);
					bw.Write(this.Unk19);
					bw.Write(this.Unk20);
					bw.Write(this.Unk21);
					bw.Write(this.Unk22);
					bw.Write(this.Unk23);
					bw.Write(this.Unk24);
					bw.Write(this.Unk25);
					bw.Write(this.Unk26);
					bw.Write(this.Unk27);
					bw.Write(this.Unk28);
					bw.Write(this.Unk29);
					bw.Write(this.Unk30);
					bw.Write(this.Unk31);
					bw.Write(this.WRDArchive);
					bw.Write(this.SubroutineArchive);
					bw.Write(this.Unk32);
					bw.Write(this.Unk33);
					bw.Write(this.Unk34);
					bw.Write(this.WRDFile);
					bw.Write(this.SubroutineWRD);
					bw.Write(this.Unk35);
					bw.Write(this.Unk36);
					bw.Write(this.Unk37);
					bw.Write(this.TextArchive);
					bw.Write(this.SubroutineTextArchive);
					bw.Write(this.Unk38);
					bw.Write(this.Unk39);
					bw.Write(this.Unk40);
					bw.Write(this.TextSTX);
					bw.Write(this.SubroutineSTX);
					bw.Write(this.Unk41);
					bw.Write(this.Unk42);
					bw.Write(this.Unk43);
					bw.Write(this.WRDMap);
					bw.Write(this.Unk44);
					bw.Write(this.Unk45);
					bw.Write(this.Unk46);
					bw.Write(this.CurrentMapID);
					bw.Write(this.Unk47);
					bw.Write(this.BGMIndex);
					bw.Write(this.Unk48);
					bw.Write(this.Unk49);
					bw.Write(this.CurrentBGM);
					bw.Write(this.Unk50);
					bw.Write(this.CurrentSFX);
					bw.Write(this.Unk51);
					bw.Write(this.Unk52);
					bw.Write(this.Unk53);
					bw.Write(this.CurrentLine);
					bw.Write(this.Unk54);
					bw.Write(this.Unk55);
					bw.Write(this.Unk56);
					bw.Write(this.Unk57);
					bw.Write(this.Unk58);
					bw.Write(this.Unk59);
					bw.Write(this.Unk60);
					bw.Write(this.Unk61);
					bw.Write(this.Voiceline1);
					bw.Write(this.Voiceline2);
					bw.Write(this.Voiceline3);
					bw.Write(this.Voiceline4);
					bw.Write(this.Voiceline5);
					bw.Write(this.Voiceline6);
					bw.Write(this.Voiceline7);
					bw.Write(this.Voiceline8);
					bw.Write(this.Voiceline9);
					bw.Write(this.Voiceline10);
					bw.Write(this.Voiceline11);
					bw.Write(this.Voiceline12);
					bw.Write(this.Voiceline13);
					bw.Write(this.Voiceline14);
					bw.Write(this.Voiceline15);
					bw.Write(this.Voiceline16);
					bw.Write(this.Unk62);
					bw.Write(this.Unk63);
					bw.Write(this.Unk64);
					bw.Write(this.CurrentMapID_Again);
					bw.Write(this.Unk65);
					bw.Write(this.Unk66);
					bw.Write(this.Unk67);
					bw.Write(this.VoiceLanguageEnglish);
					bw.Write(this.Setting2);
					bw.Write(this.InvertX);
					bw.Write(this.DateFormat);
					bw.Write(this.Unk68);
					bw.Write(this.Unk69);
					bw.Write(this.Unk70);
					bw.Write(this.LastBytes);
				}
			}
		}
	}
}
